
GRID_HEIGHT = 10
GRID_WIDTH = 10

GRID_X_SPACING = 72
GRID_Y_SPACING = 72

SCREEN_WIDTH = GRID_HEIGHT * GRID_X_SPACING
SCREEN_HEIGHT = GRID_WIDTH * GRID_Y_SPACING

MULTIPLAYER_INPUT_BOX = (150, 320, 300, 60)

FPS = 20
ANIMATION_TIMING = 400
