from pygame import Rect

GRID_HEIGHT = 10
GRID_WIDTH = 10

GRID_X_SPACING = 72
GRID_Y_SPACING = 72

SCREEN_WIDTH = GRID_HEIGHT * GRID_X_SPACING
SCREEN_HEIGHT = GRID_WIDTH * GRID_Y_SPACING

HEADER_HEIGHT = 32
HEADER_ICON_CTR = (20, HEADER_HEIGHT // 2)
HEADER_NAME_POS = (32 + 10, HEADER_HEIGHT // 2)
HEADER_CLOSE_RECT = Rect(SCREEN_WIDTH - 36, 0, 36, HEADER_HEIGHT)
MULTIPLAYER_INPUT_BOX = Rect(150, 320, 300, 60)

FPS = 100
ANIMATION_TIMING = 400
