
COM_CONNECT = '!CONNECT'
COM_CONNECTION_CHECK = '!CONNECTION_CHECK'
COM_PAIR = '!PAIR'
COM_DISCONNECT = '!DISCONNECT'
COM_GAME_READINESS = '!GAME_READINESS'
COM_GAME_WAIT = '!GAME_WAIT'
COM_SHOOT = '!SHOOT'
COM_OPPONENT_SHOT = '!OPPONENT_SHOT'